"""Form Select Field choices"""

SS_CHOICES = [("Abstract", "Abstract"),
              ("Animals/Wildlife", "Animals/Wildlife"),
              ("Arts", "Arts"),
              ("Backgrounds/Textures", "Backgrounds/Textures"),
              ("Beauty/Fashion", "Beauty/Fashion"),
              ("Buildings/Landmarks", "Buildings/Landmarks"),
              ("Business/Finance", "Business/Finance"),
              ("Celebrities", "Celebrities"),
              ("Education", "Education"),
              ("Food and Drink", "Food and Drink"),
              ("Healthcare/Medical", "Healthcare/Medical"),
              ("Holidays", "Holidays"),
              ("Industrial", "Industrial"),
              ("Interiors", "Interiors"),
              ("Miscellaneous", "Miscellaneous"),
              ("Nature", "Nature"),
              ("Objects", "Objects"),
              ("Parks/Outdoor", "Parks/Outdoor"),
              ("People", "People"),
              ("Religion", "Religion"),
              ("Science", "Science"),
              ("Signs/Symbols", "Signs/Symbols"),
              ("Sports/Recreation", "Sports/Recreation"),
              ("Technology", "Technology"),
              ("Transportation", "Transportation"),
              ("Vintage", "Vintage")]

# SS_CHOICES_DICT = dict(SS_CHOICES)
